### ISSUE TITLE
Peer Review #4- Sitemap

### ISSUE THREAD

**Issue by Tierneygregory** [haniicorn/PBJWebsite#8]
Hi! I could be wrong about this but I think the sitemap is something different than your nav bar? And its supposed to be at the end of your home page like apple has.... I think haha

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sitemap</title>
    <style>
      @import url("https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap");
      html,
      body {
        font-family: "Inter";
      }
      h1 {
        font-weight: bold;
        text-align: center;
        color: #7a4081;
      }
      .nav {
        display: flex;
        justify-content: row;
        justify-content: space-around;
        align-items: center;
        align-content: stretch;
        margin-top: 5px;
        font-weight: bold;
        align-items: end;
        flex-wrap: nowrap;
      }

      .item {
        margin-left: 5px;
        margin-right: 5px;
      }

      img.logo {
        display: inline-block;
        height: 8vh;
        margin-top: 10px;
      }
      .divider {
        width: 20%;
      }

      a:link,
      a:visited {
        text-decoration: none;
        color: black;
      }

      a:hover {
        color: #7a4081;
      }

      .list {
        margin-left: auto;
        margin-right: auto;
        width: 25vh;
      }
    </style>
  </head>
  <body>
    <div class="nav">
      <div class="item logo">
        <a href="index.html"
          ><img class="logo" src="images/pbjlogo.png" alt="pbj logo"
        /></a>
        <a href="index.html" class="pbj-index"
          >Product, Building, &amp; Jammin&apos;</a
        >
      </div>

      <div class="divider"></div>

      <div class="item active"><a href="about.html">About</a></div>
      <div class="item"><a href="events.html">Events</a></div>
      <div class="item"><a href="gallery.html">Gallery</a></div>
      <div class="item"><a href="resources.html">Resources</a></div>
      <div class="item"><a href="contact.html">Contact</a></div>
    </div>

    <h1>this is the pb&j sitemap</h1>
    <div class="list">
      <hr />
      <ul>
        <li><a href="index.html">Home</a></li>
        <li><a href="about.html">About</a></li>
        <li><a href="events.html">Events</a></li>
        <li><a href="gallery.html">Gallery</a></li>
        <li><a href="resources.html">Resources</a></li>
        <li><a href="contact.html">Contact</a></li>
      </ul>
    </div>
  </body>
</html>

**Comment by haniicorn** [comment]
fixed! made a sitemap tab on the nav bar :)
